import Head from 'next/head'
import React from 'react'
import About from '../../components/home/About'
import Team from '../../components/team'
import Goal from '../../components/about/goal'
export const metadata = {
  title: 'test || Comma Technologies',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <div>
      <About className="" />
      <Goal class="w-full bg-gradient-to-r px-[1rem] to-black from-[#0b0b3e]" />
      <Team />
    </div>
  )
}

export default page